//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ImageClient.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImageServiceSoap", Namespace="http://localhost:49191/imageService.asmx")]
    public partial class ImageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback toGrayScaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback toFlipImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback toFlipAndGrayscaleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImageService() {
            this.Url = global::ImageClient.Properties.Settings.Default.ImageClient_localhost_ImageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event toGrayScaleCompletedEventHandler toGrayScaleCompleted;
        
        /// <remarks/>
        public event toFlipImageCompletedEventHandler toFlipImageCompleted;
        
        /// <remarks/>
        public event toFlipAndGrayscaleCompletedEventHandler toFlipAndGrayscaleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:49191/imageService.asmx/toGrayScale", RequestNamespace="http://localhost:49191/imageService.asmx", ResponseNamespace="http://localhost:49191/imageService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] toGrayScale([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            object[] results = this.Invoke("toGrayScale", new object[] {
                        data});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void toGrayScaleAsync(byte[] data) {
            this.toGrayScaleAsync(data, null);
        }
        
        /// <remarks/>
        public void toGrayScaleAsync(byte[] data, object userState) {
            if ((this.toGrayScaleOperationCompleted == null)) {
                this.toGrayScaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OntoGrayScaleOperationCompleted);
            }
            this.InvokeAsync("toGrayScale", new object[] {
                        data}, this.toGrayScaleOperationCompleted, userState);
        }
        
        private void OntoGrayScaleOperationCompleted(object arg) {
            if ((this.toGrayScaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.toGrayScaleCompleted(this, new toGrayScaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:49191/imageService.asmx/toFlipImage", RequestNamespace="http://localhost:49191/imageService.asmx", ResponseNamespace="http://localhost:49191/imageService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] toFlipImage([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            object[] results = this.Invoke("toFlipImage", new object[] {
                        data});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void toFlipImageAsync(byte[] data) {
            this.toFlipImageAsync(data, null);
        }
        
        /// <remarks/>
        public void toFlipImageAsync(byte[] data, object userState) {
            if ((this.toFlipImageOperationCompleted == null)) {
                this.toFlipImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OntoFlipImageOperationCompleted);
            }
            this.InvokeAsync("toFlipImage", new object[] {
                        data}, this.toFlipImageOperationCompleted, userState);
        }
        
        private void OntoFlipImageOperationCompleted(object arg) {
            if ((this.toFlipImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.toFlipImageCompleted(this, new toFlipImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:49191/imageService.asmx/toFlipAndGrayscale", RequestNamespace="http://localhost:49191/imageService.asmx", ResponseNamespace="http://localhost:49191/imageService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] toFlipAndGrayscale([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            object[] results = this.Invoke("toFlipAndGrayscale", new object[] {
                        data});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void toFlipAndGrayscaleAsync(byte[] data) {
            this.toFlipAndGrayscaleAsync(data, null);
        }
        
        /// <remarks/>
        public void toFlipAndGrayscaleAsync(byte[] data, object userState) {
            if ((this.toFlipAndGrayscaleOperationCompleted == null)) {
                this.toFlipAndGrayscaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OntoFlipAndGrayscaleOperationCompleted);
            }
            this.InvokeAsync("toFlipAndGrayscale", new object[] {
                        data}, this.toFlipAndGrayscaleOperationCompleted, userState);
        }
        
        private void OntoFlipAndGrayscaleOperationCompleted(object arg) {
            if ((this.toFlipAndGrayscaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.toFlipAndGrayscaleCompleted(this, new toFlipAndGrayscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void toGrayScaleCompletedEventHandler(object sender, toGrayScaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class toGrayScaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal toGrayScaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void toFlipImageCompletedEventHandler(object sender, toFlipImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class toFlipImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal toFlipImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void toFlipAndGrayscaleCompletedEventHandler(object sender, toFlipAndGrayscaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class toFlipAndGrayscaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal toFlipAndGrayscaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591